# Generated by Django 4.1.7 on 2023-03-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_client_options_alter_links_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис ресурсу'),
        ),
    ]
