# Generated by Django 4.1.7 on 2023-03-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_links_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link_type',
            field=models.CharField(choices=[('YOUTUBE', 'Youtube'), ('TWITTER', 'Twitter'), ('TELEGRAM', 'Telegram'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('TIKTOK', 'TikTok'), ('VIBER', 'Viber'), ('OTHER', 'Інший тип')], default='OTHER', max_length=10, verbose_name='Статус посилання'),
        ),
    ]
