# Generated by Django 4.1.7 on 2023-03-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_rename_user_links_client_links_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_creator', to='admin_panel.client', verbose_name='Користувач'),
        ),
    ]
